### ISSUE TITLE
When run "python pydecoders/decode_wfst_main.py examples/hkust/conf/hkust.conf", I got an "out of range" issues:

### ISSUE THREAD

**Issue by gaojingqian** [athena-team/athena-decoder#15]
Traceback (most recent call last):
  File "pydecoders/decode_wfst_main.py", line 89, in <module>
    decoder.decode(enc_outputs, initial_packed_states, e2e_model.inference_one_step)
  File "/algdata03/jingqian.gao/code/fromGit/athena-decoder/pydecoders/decoders/wfst_decoder.py", line 80, in decode
    weight_cutoff = self.process_emitting(encoder_outputs, inference_one_step_fn)
  File "/algdata03/jingqian.gao/code/fromGit/athena-decoder/pydecoders/decoders/wfst_decoder.py", line 168, in process_emitting
    if self.eos == np.argmax(all_log_scores[seq_id]):
IndexError: list index out of range

What can I do?

**Comment by godjealous** [comment]
where do you get the acoustic scores ?
We have provide completed examples in https://github.com/athena-team/athena#5-decoding-with-wfst

**Comment by gaojingqian** [comment]
I downloaded the athena-decoder fold only.It cannot run correctly follow README.md, and an error occurred that is lack of some txt files. I added these files according to the historical commit version:06a6d95e0e0d8d18aaa7f15f94464eef8fc02bf7. Then, when run this command(following README.md in athena-decoder ), this error happens.

**Comment by Some-random** [comment]
> I downloaded the athena-decoder fold only.It cannot run correctly follow README.md, and an error occurred that is lack of some txt files. I added these files according to the historical commit version:06a6d95e0e0d8d18aaa7f15f94464eef8fc02bf7. Then, when run this command(following README.md in athena-decoder ), this error happens.

You need to clone [athena](https://github.com/athena-team/athena) and train the acoustic model there first.

**Comment by Some-random** [comment]
To run the whole acoustic training & WFST decoding process, please follow this [recipe](https://github.com/athena-team/athena/blob/master/examples/asr/aishell/run.sh) change 'use_wfst' to true.
